#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# FamilyCare backend - one-time server setup (Oracle Cloud / any Ubuntu VM)
#
# Run from the project folder on the server:
#   bash deploy/setup-server.sh <domain> <email> [frontend-url]
#
# Example:
#   bash deploy/setup-server.sh familycare.duckdns.org me@gmail.com https://familycare.vercel.app
#
# What it does:
#   1. Sets timezone to Asia/Kolkata (medication reminders use server time)
#   2. Opens ports 80/443 in the server's own firewall (Oracle blocks them by default)
#   3. Installs Node.js 22, Docker, nginx, certbot and pm2
#   4. Generates strong passwords + JWT secret and writes all .env files
#   5. Starts MySQL + Redis (Docker) and the 4 Node services (pm2)
#   6. Configures nginx and gets a free HTTPS certificate (Let's Encrypt)
#
# Safe to run again: it keeps existing passwords (stored in ./.env) and
# just re-applies the configuration.
# ---------------------------------------------------------------------------
set -euo pipefail

DOMAIN="${1:-}"
EMAIL="${2:-}"
FRONTEND_URL_ARG="${3:-}"

if [[ -z "$DOMAIN" || -z "$EMAIL" ]]; then
  echo "Usage: bash deploy/setup-server.sh <domain> <email> [frontend-url]"
  echo "Example: bash deploy/setup-server.sh familycare.duckdns.org me@gmail.com https://familycare.vercel.app"
  exit 1
fi

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"
SERVICES=(auth-service family-service health-service api-gateway)

step() { echo -e "\n\033[1;36m==> $*\033[0m"; }
warn() { echo -e "\033[1;33m[!] $*\033[0m"; }

# ── 1. Timezone ────────────────────────────────────────────────────────────
step "Setting timezone to Asia/Kolkata"
sudo timedatectl set-timezone Asia/Kolkata

# ── 2. System packages + firewall ─────────────────────────────────────────
step "Installing system packages (nginx, certbot, git, firewall tools)"
echo "iptables-persistent iptables-persistent/autosave_v4 boolean true" | sudo debconf-set-selections
echo "iptables-persistent iptables-persistent/autosave_v6 boolean true" | sudo debconf-set-selections
sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ca-certificates curl git openssl nginx certbot python3-certbot-nginx iptables-persistent

step "Opening ports 80 and 443 in the server firewall"
# Oracle's Ubuntu images ship iptables rules that reject everything except SSH.
# (You must ALSO allow 80/443 in the Oracle Cloud "Security List" - see DEPLOY.md.)
for port in 80 443; do
  if ! sudo iptables -C INPUT -p tcp -m state --state NEW --dport "$port" -j ACCEPT 2>/dev/null; then
    sudo iptables -I INPUT 1 -p tcp -m state --state NEW --dport "$port" -j ACCEPT
  fi
done
sudo netfilter-persistent save

# ── 3. Node.js, Docker, pm2 ───────────────────────────────────────────────
NODE_MAJOR=0
if command -v node >/dev/null 2>&1; then NODE_MAJOR="$(node -v | sed 's/^v//' | cut -d. -f1)"; fi
if (( NODE_MAJOR < 20 )); then
  step "Installing Node.js 22"
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
fi

if ! command -v docker >/dev/null 2>&1; then
  step "Installing Docker"
  curl -fsSL https://get.docker.com | sudo sh
fi
sudo usermod -aG docker "$USER" || true
sudo systemctl enable --now docker

if ! command -v pm2 >/dev/null 2>&1; then
  step "Installing pm2"
  sudo npm install -g pm2
fi

# ── 4. Secrets and .env files ─────────────────────────────────────────────
step "Writing configuration (.env files)"
if [[ ! -f .env ]]; then
  cat > .env <<EOF
# Master settings for this server. Service .env files are generated from this.
# Keep this file private. Re-run deploy/setup-server.sh after editing it.
MYSQL_ROOT_PASSWORD=$(openssl rand -hex 16)
MYSQL_DATABASE=familycare
MYSQL_USER=familycare
MYSQL_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 48)
ALLOWED_ORIGINS=*
FRONTEND_URL=
EOF
  echo "Generated new passwords and JWT secret in $APP_DIR/.env"
else
  echo "Reusing existing $APP_DIR/.env"
fi

if [[ -n "$FRONTEND_URL_ARG" ]]; then
  FRONTEND_URL_ARG="${FRONTEND_URL_ARG%/}"
  sed -i "s#^ALLOWED_ORIGINS=.*#ALLOWED_ORIGINS=${FRONTEND_URL_ARG}#" .env
  sed -i "s#^FRONTEND_URL=.*#FRONTEND_URL=${FRONTEND_URL_ARG}#" .env
fi
chmod 600 .env

set -a; source ./.env; set +a

write_db_env() {  # $1 = service folder, $2 = port
  cat > "$1/.env" <<EOF
# Generated by deploy/setup-server.sh - edit ../.env instead and re-run the script
PORT=$2
JWT_SECRET=$JWT_SECRET
DB_HOST=127.0.0.1
DB_PORT=3307
DB_USER=$MYSQL_USER
DB_PASSWORD=$MYSQL_PASSWORD
DB_NAME=$MYSQL_DATABASE
EOF
}
write_db_env auth-service 3001
write_db_env family-service 3002
echo "FRONTEND_URL=${FRONTEND_URL:-https://$DOMAIN}" >> family-service/.env
write_db_env health-service 3003
echo "REDIS_URL=redis://127.0.0.1:6379" >> health-service/.env
cat > api-gateway/.env <<EOF
# Generated by deploy/setup-server.sh - edit ../.env instead and re-run the script
PORT=3000
JWT_SECRET=$JWT_SECRET
AUTH_SERVICE_URL=http://127.0.0.1:3001
FAMILY_SERVICE_URL=http://127.0.0.1:3002
HEALTH_SERVICE_URL=http://127.0.0.1:3003
ALLOWED_ORIGINS=$ALLOWED_ORIGINS
EOF
for s in "${SERVICES[@]}"; do chmod 600 "$s/.env"; done

# ── 5. Databases + Node services ──────────────────────────────────────────
step "Starting MySQL and Redis (Docker)"
sudo docker compose up -d mysql redis

echo -n "Waiting for MySQL to be ready"
for i in $(seq 1 60); do
  status="$(sudo docker inspect -f '{{.State.Health.Status}}' familycare-mysql 2>/dev/null || echo starting)"
  if [[ "$status" == "healthy" ]]; then echo " ok"; break; fi
  echo -n "."; sleep 5
  if (( i == 60 )); then echo; warn "MySQL did not become healthy. Check: sudo docker logs familycare-mysql"; exit 1; fi
done

step "Installing Node dependencies"
for s in "${SERVICES[@]}"; do
  echo "-- $s"
  (cd "$s" && (npm ci --omit=dev --no-audit --no-fund || npm install --omit=dev --no-audit --no-fund))
done

step "Starting services with pm2"
pm2 startOrReload ecosystem.config.js --update-env
pm2 save
sudo env PATH="$PATH" "$(command -v pm2)" startup systemd -u "$USER" --hp "$HOME" >/dev/null
echo "pm2 will restart the services automatically after a reboot."

echo -n "Checking the API gateway"
for i in $(seq 1 20); do
  if curl -fsS http://127.0.0.1:3000/gateway/health >/dev/null 2>&1; then echo " ok"; break; fi
  echo -n "."; sleep 2
done
curl -fsS http://127.0.0.1:3000/gateway/status || warn "Gateway status check failed - see: pm2 logs"
echo

# ── 6. nginx + HTTPS ──────────────────────────────────────────────────────
step "Configuring nginx for $DOMAIN"
sed "s/__DOMAIN__/$DOMAIN/g" deploy/nginx-familycare.conf.template | sudo tee /etc/nginx/sites-available/familycare >/dev/null
sudo ln -sf /etc/nginx/sites-available/familycare /etc/nginx/sites-enabled/familycare
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl enable nginx
sudo systemctl reload nginx

PUBLIC_IP="$(curl -fsS -4 https://api.ipify.org 2>/dev/null || true)"
DNS_IP="$(getent ahostsv4 "$DOMAIN" 2>/dev/null | awk 'NR==1{print $1}')"

step "Getting HTTPS certificate"
if [[ -n "$PUBLIC_IP" && "$PUBLIC_IP" != "$DNS_IP" ]]; then
  warn "$DOMAIN points to '${DNS_IP:-nothing}', but this server's IP is $PUBLIC_IP."
  warn "Fix the DNS record (e.g. on duckdns.org), wait a minute, then run:"
  warn "  sudo certbot --nginx -d $DOMAIN -m $EMAIL --agree-tos --non-interactive --redirect"
else
  sudo certbot --nginx -d "$DOMAIN" -m "$EMAIL" --agree-tos --non-interactive --redirect --keep-until-expiring
fi

step "Done!"
cat <<EOF

  API URL:        https://$DOMAIN
  Health check:   https://$DOMAIN/gateway/status
  Allowed origin: $ALLOWED_ORIGINS

  Use this in Vercel as the environment variable:
      VITE_API_URL=https://$DOMAIN

  Useful commands:
      pm2 status                 # are the 4 services running?
      pm2 logs                   # live logs
      bash deploy/update.sh      # after you push new code to GitHub
EOF
